FLASK_API_URL = "http://127.0.0.1:5000"
OPENAI_API_KEY = "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"